version: "3.8"

services:
  praxiaskill-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: praxiaskill-backend
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - env.production
    depends_on:
      - praxiaskill-mongo
      - redis
    networks:
      - praxiaskill-net

  praxiaskill-mongo:
    image: mongo:7.0.0
    container_name: praxiaskill-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - praxiaskill-net

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - praxiaskill-net

volumes:
  mongo-data:
  redis-data:

networks:
  praxiaskill-net:
    driver: bridge